MODELS:
  - name: gpt-3.5-turbo
    tokens: 4096
  - name: gpt-3.5-turbo-16k
    tokens: 16385
APPROX_CHUNK_SIZE: 250
DEFAULT_MODEL: gpt-3.5-turbo
N_RESERVE_RESPONSE_TOKENS: 500
TEMPERATURE: 0.2
SYSTEM_PROMPT: "Use the following pieces of context (delimited by three quotes) to answer the question at the end.  If you don't know the answer, just say that you don't know, do not try to make up an answer. At the end of your commentary suggest a further question that can be answered by the paragraphs provided."
